/* GENERATED by tools/build-sw.js — do not edit by hand.
   Re-run `npm run sw` after changing the app, farm-geo.js, vendor/ or icons/.
   VERSION is a hash of those files, so it changes when they do. */
const VERSION = 'f6a239d67507';
const CACHE = 'ut-turf-farm-' + VERSION;
/* v2 on 2026-09-16: v1 stored every photo sealed (see tileFetch below) and a
   phone that ran out of room showed green squares. Renaming it is what makes
   activate() below throw the bloated v1 away. */
const TILES = 'ut-turf-tiles-v2';
const TILE_MAX = 400;          /* roughly a few sessions of panning */

const SHELL = [
  "UT-TurfFarm-App.html",
  "app-01-shell.js",
  "app-02-fieldlog-sync.js",
  "app-03-people.js",
  "app-04-spray-inventory.js",
  "app-05-tasks-clock.js",
  "farm-geo.js",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-192.png",
  "icons/icon-maskable-512.png",
  "manifest.webmanifest",
  "vendor/firebase/firebase-app-compat.js",
  "vendor/firebase/firebase-auth-compat.js",
  "vendor/firebase/firebase-firestore-compat.js",
  "vendor/fonts/archivo-latin-600-normal.woff2",
  "vendor/fonts/archivo-latin-700-normal.woff2",
  "vendor/fonts/archivo-latin-800-normal.woff2",
  "vendor/fonts/archivo-latin-900-normal.woff2",
  "vendor/fonts/archivo-latin-ext-600-normal.woff2",
  "vendor/fonts/archivo-latin-ext-700-normal.woff2",
  "vendor/fonts/archivo-latin-ext-800-normal.woff2",
  "vendor/fonts/archivo-latin-ext-900-normal.woff2",
  "vendor/fonts/archivo-vietnamese-600-normal.woff2",
  "vendor/fonts/archivo-vietnamese-700-normal.woff2",
  "vendor/fonts/archivo-vietnamese-800-normal.woff2",
  "vendor/fonts/archivo-vietnamese-900-normal.woff2",
  "vendor/fonts/fonts.css",
  "vendor/fonts/public-sans-latin-500-normal.woff2",
  "vendor/fonts/public-sans-latin-600-normal.woff2",
  "vendor/fonts/public-sans-latin-700-normal.woff2",
  "vendor/fonts/public-sans-latin-800-normal.woff2",
  "vendor/fonts/public-sans-latin-ext-500-normal.woff2",
  "vendor/fonts/public-sans-latin-ext-600-normal.woff2",
  "vendor/fonts/public-sans-latin-ext-700-normal.woff2",
  "vendor/fonts/public-sans-latin-ext-800-normal.woff2",
  "vendor/fonts/public-sans-vietnamese-500-normal.woff2",
  "vendor/fonts/public-sans-vietnamese-600-normal.woff2",
  "vendor/fonts/public-sans-vietnamese-700-normal.woff2",
  "vendor/fonts/public-sans-vietnamese-800-normal.woff2",
  "vendor/geoman/leaflet-geoman.css",
  "vendor/geoman/leaflet-geoman.min.js",
  "vendor/leaflet/images/layers-2x.png",
  "vendor/leaflet/images/layers.png",
  "vendor/leaflet/images/marker-icon-2x.png",
  "vendor/leaflet/images/marker-icon.png",
  "vendor/leaflet/images/marker-shadow.png",
  "vendor/leaflet/leaflet.css",
  "vendor/leaflet/leaflet.js",
  "vendor/turf/turf.min.js"
];

/* Install: fetch the whole shell before this worker is allowed to take over.
   No skipWaiting here — the page asks the user first, so a crew member is not
   reloaded out from under a half-filled form. */
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)));
});

/* Activate: drop every older version of the shell. The tile cache is keyed
   separately and deliberately survives — re-downloading imagery costs the farm
   data for no benefit. */
self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE && k !== TILES).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', e => {
  if (e.data === 'SKIP_WAITING') self.skipWaiting();
  if (e.data === 'VERSION') e.source && e.source.postMessage({ version: VERSION });
});

const isTile = u => /server\.arcgisonline\.com/.test(u);
/* The radar loop is a live picture; a cached one is a lie about the weather. */
const isLive = u => /radar\.weather\.gov/.test(u);

/* Is this a request for one of OUR OWN files? Anything else belongs to another
   website and this worker must not stand in front of it -- see the fetch
   handler below. A URL we cannot even parse is treated as ours, because that
   keeps the old behaviour for anything we might have precached. */
const isOurs = u => {
  try { return new URL(u, self.location.href).origin === self.location.origin; }
  catch (err) { return true; }
};

/* Ask the imagery server for the photo OPENLY (cors), not the way the map
   itself asks for it.

   The map's plain <img> request gets back a sealed ("opaque") reply: the
   picture works, but the phone is not allowed to know how big it is, so it
   books every one against the app's storage as several megabytes to be safe.
   Measured on 2026-09-16: 30 photos of about 10 KB each booked 225 MB. With
   up to 400 kept, a phone ran out of room within a few screens of panning --
   and from then on every photo arrived and was then thrown away, which is the
   green squares on the map. The Esri server allows open requests, so asking
   that way stores the real 10 KB. If an open request is ever refused, fall
   back to the sealed one: a photo on screen matters more than a saved one. */
async function tileFetch(req) {
  try { return await fetch(req.url, { mode: 'cors', credentials: 'omit' }); }
  catch (err) { return fetch(req); }
}

/* Saving a photo is a nice-to-have. It must never be able to cost the photo
   itself, so every failure in here is swallowed -- the caller has already
   handed the picture to the map. */
async function tileKeep(url, res) {
  try {
    const c = await caches.open(TILES);
    await c.put(url, res);
    const keys = await c.keys();
    if (keys.length > TILE_MAX) await Promise.all(keys.slice(0, keys.length - TILE_MAX).map(k => c.delete(k)));
  } catch (err) {}
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = req.url;

  if (isLive(url)) return;                       /* straight to the network */

  if (isTile(url)) {
    /* Imagery already seen keeps working in a dead spot. */
    e.respondWith((async () => {
      const hit = await caches.match(url);
      if (hit) return hit;
      let res;
      try { res = await tileFetch(req); }
      catch (err) { return new Response('', { status: 504 }); }
      /* Only a real, readable photo is worth keeping; a sealed fallback would
         bring the storage problem straight back. */
      /* waitUntil only asks the phone to stay awake long enough to finish
         saving. If a browser refuses that request, the photo must still go
         to the map, so a refusal is ignored rather than allowed to throw. */
      if (res.ok && res.type !== 'opaque') {
        const keep = tileKeep(url, res.clone());
        try { e.waitUntil(keep); } catch (err) {}
      }
      return res;
    })());
    return;
  }

  /* SOMEBODY ELSE'S WEBSITE: hands off, straight to the network.
     -------------------------------------------------------------------
     This line is load-bearing and it was missing until 2026-08-27.

     The shared database does not fetch a page and finish. It holds ONE
     long request open to Google and Google pushes changes down it as they
     happen. Answering that request through e.respondWith() below breaks
     it: the reply is collected here and handed over in one piece at the
     end, and there is no end, so the app waits forever. It never errors --
     it just never hears back.

     The symptom, and it cost a day: every drawer stuck on "Connected --
     waiting for the shared copy", nothing red, and nothing ever uploaded,
     because a phone deliberately sends nothing up until it has heard from
     the shared copy once. Signing in still worked, which made the
     connection look fine -- sign-in is a POST, and POSTs never reach this
     handler at all (see the first line above).

     Map imagery is the one deliberate exception and it is handled above,
     before this line. Everything else off this site -- Google, the
     weather -- goes straight out. */
  if (!isOurs(url)) return;

  /* A navigation always lands on the app, even offline. */
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try { return await fetch(req); }
      catch (err) { return (await caches.match('UT-TurfFarm-App.html')) || Response.error(); }
    })());
    return;
  }

  /* Everything else on this site: the cache is the source of truth for this
     version, since the shell is versioned as a set and cannot be half-old. */
  e.respondWith((async () => {
    const hit = await caches.match(req, { ignoreSearch: false });
    if (hit) return hit;
    try { return await fetch(req); }
    catch (err) { return new Response('', { status: 504 }); }
  })());
});
