/* GENERATED by tools/build-sw.js — do not edit by hand.
   Re-run `npm run sw` after changing the app, farm-geo.js, vendor/ or icons/.
   VERSION is a hash of those files, so it changes when they do. */
const VERSION = '321b39c4bb64';
const CACHE = 'ut-turf-farm-' + VERSION;
const TILES = 'ut-turf-tiles-v1';
const TILE_MAX = 400;          /* roughly a few sessions of panning */

const SHELL = [
  "UT-TurfFarm-App.html",
  "farm-geo.js",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-192.png",
  "icons/icon-maskable-512.png",
  "manifest.webmanifest",
  "vendor/firebase/firebase-app-compat.js",
  "vendor/firebase/firebase-auth-compat.js",
  "vendor/firebase/firebase-firestore-compat.js",
  "vendor/fonts/archivo-latin-600-normal.woff2",
  "vendor/fonts/archivo-latin-700-normal.woff2",
  "vendor/fonts/archivo-latin-800-normal.woff2",
  "vendor/fonts/archivo-latin-900-normal.woff2",
  "vendor/fonts/archivo-latin-ext-600-normal.woff2",
  "vendor/fonts/archivo-latin-ext-700-normal.woff2",
  "vendor/fonts/archivo-latin-ext-800-normal.woff2",
  "vendor/fonts/archivo-latin-ext-900-normal.woff2",
  "vendor/fonts/archivo-vietnamese-600-normal.woff2",
  "vendor/fonts/archivo-vietnamese-700-normal.woff2",
  "vendor/fonts/archivo-vietnamese-800-normal.woff2",
  "vendor/fonts/archivo-vietnamese-900-normal.woff2",
  "vendor/fonts/fonts.css",
  "vendor/fonts/public-sans-latin-500-normal.woff2",
  "vendor/fonts/public-sans-latin-600-normal.woff2",
  "vendor/fonts/public-sans-latin-700-normal.woff2",
  "vendor/fonts/public-sans-latin-800-normal.woff2",
  "vendor/fonts/public-sans-latin-ext-500-normal.woff2",
  "vendor/fonts/public-sans-latin-ext-600-normal.woff2",
  "vendor/fonts/public-sans-latin-ext-700-normal.woff2",
  "vendor/fonts/public-sans-latin-ext-800-normal.woff2",
  "vendor/fonts/public-sans-vietnamese-500-normal.woff2",
  "vendor/fonts/public-sans-vietnamese-600-normal.woff2",
  "vendor/fonts/public-sans-vietnamese-700-normal.woff2",
  "vendor/fonts/public-sans-vietnamese-800-normal.woff2",
  "vendor/geoman/leaflet-geoman.css",
  "vendor/geoman/leaflet-geoman.min.js",
  "vendor/leaflet/images/layers-2x.png",
  "vendor/leaflet/images/layers.png",
  "vendor/leaflet/images/marker-icon-2x.png",
  "vendor/leaflet/images/marker-icon.png",
  "vendor/leaflet/images/marker-shadow.png",
  "vendor/leaflet/leaflet.css",
  "vendor/leaflet/leaflet.js",
  "vendor/turf/turf.min.js"
];

/* Install: fetch the whole shell before this worker is allowed to take over.
   No skipWaiting here — the page asks the user first, so a crew member is not
   reloaded out from under a half-filled form. */
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)));
});

/* Activate: drop every older version of the shell. The tile cache is keyed
   separately and deliberately survives — re-downloading imagery costs the farm
   data for no benefit. */
self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE && k !== TILES).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', e => {
  if (e.data === 'SKIP_WAITING') self.skipWaiting();
  if (e.data === 'VERSION') e.source && e.source.postMessage({ version: VERSION });
});

const isTile = u => /server\.arcgisonline\.com/.test(u);
/* The radar loop is a live picture; a cached one is a lie about the weather. */
const isLive = u => /radar\.weather\.gov/.test(u);

/* Is this a request for one of OUR OWN files? Anything else belongs to another
   website and this worker must not stand in front of it -- see the fetch
   handler below. A URL we cannot even parse is treated as ours, because that
   keeps the old behaviour for anything we might have precached. */
const isOurs = u => {
  try { return new URL(u, self.location.href).origin === self.location.origin; }
  catch (err) { return true; }
};

async function tilePut(req, res) {
  const c = await caches.open(TILES);
  await c.put(req, res.clone());
  const keys = await c.keys();
  if (keys.length > TILE_MAX) await Promise.all(keys.slice(0, keys.length - TILE_MAX).map(k => c.delete(k)));
  return res;
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = req.url;

  if (isLive(url)) return;                       /* straight to the network */

  if (isTile(url)) {
    /* Imagery already seen keeps working in a dead spot. */
    e.respondWith((async () => {
      const hit = await caches.match(req);
      if (hit) return hit;
      try { return await tilePut(req, await fetch(req)); }
      catch (err) { return new Response('', { status: 504 }); }
    })());
    return;
  }

  /* SOMEBODY ELSE'S WEBSITE: hands off, straight to the network.
     -------------------------------------------------------------------
     This line is load-bearing and it was missing until 2026-08-27.

     The shared database does not fetch a page and finish. It holds ONE
     long request open to Google and Google pushes changes down it as they
     happen. Answering that request through e.respondWith() below breaks
     it: the reply is collected here and handed over in one piece at the
     end, and there is no end, so the app waits forever. It never errors --
     it just never hears back.

     The symptom, and it cost a day: every drawer stuck on "Connected --
     waiting for the shared copy", nothing red, and nothing ever uploaded,
     because a phone deliberately sends nothing up until it has heard from
     the shared copy once. Signing in still worked, which made the
     connection look fine -- sign-in is a POST, and POSTs never reach this
     handler at all (see the first line above).

     Map imagery is the one deliberate exception and it is handled above,
     before this line. Everything else off this site -- Google, the
     weather -- goes straight out. */
  if (!isOurs(url)) return;

  /* A navigation always lands on the app, even offline. */
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try { return await fetch(req); }
      catch (err) { return (await caches.match('UT-TurfFarm-App.html')) || Response.error(); }
    })());
    return;
  }

  /* Everything else on this site: the cache is the source of truth for this
     version, since the shell is versioned as a set and cannot be half-old. */
  e.respondWith((async () => {
    const hit = await caches.match(req, { ignoreSearch: false });
    if (hit) return hit;
    try { return await fetch(req); }
    catch (err) { return new Response('', { status: 504 }); }
  })());
});
