/*
 * Rebuilds vendor/ from node_modules.
 *
 * The app loads Leaflet, Geoman, Turf and its two fonts from vendor/ rather
 * than from a CDN, so that a CDN changing a URL cannot take the farm's app
 * down and nobody has to diagnose it. This script is how vendor/ is produced,
 * so none of it is hand-maintained.
 *
 *   npm install leaflet@1.9.4 @geoman-io/leaflet-geoman-free@2.16.0 @turf/turf@7 \
 *               @fontsource/archivo @fontsource/public-sans \
 *               firebase@12.18.0
 *   node tools/build-vendor.js
 *
 * Pin the versions when you re-run it: an unpinned upgrade is exactly the kind
 * of surprise vendoring exists to prevent.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const NM = path.join(ROOT, 'node_modules');
const OUT = path.join(ROOT, 'vendor');

/* Weights the app actually asks for. Anything else is dead weight in the repo. */
const FONTS = [
  { pkg: 'archivo', weights: [600, 700, 800, 900] },
  { pkg: 'public-sans', weights: [500, 600, 700, 800] },
];

function mkdir(p) { fs.mkdirSync(p, { recursive: true }); }
function copy(from, to) { mkdir(path.dirname(to)); fs.copyFileSync(from, to); return 1; }
function need(p) {
  if (!fs.existsSync(p)) { console.error('missing: ' + p + '\nrun npm install first'); process.exit(1); }
  return p;
}

let n = 0;
mkdir(OUT);

n += copy(need(path.join(NM, 'leaflet/dist/leaflet.css')), path.join(OUT, 'leaflet/leaflet.css'));
n += copy(need(path.join(NM, 'leaflet/dist/leaflet.js')), path.join(OUT, 'leaflet/leaflet.js'));
/* leaflet.css points at these by relative path — without them the layers
   control and the default marker render as broken images. */
fs.readdirSync(need(path.join(NM, 'leaflet/dist/images'))).forEach(f => {
  n += copy(path.join(NM, 'leaflet/dist/images', f), path.join(OUT, 'leaflet/images', f));
});

n += copy(need(path.join(NM, '@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css')), path.join(OUT, 'geoman/leaflet-geoman.css'));
n += copy(need(path.join(NM, '@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.min.js')), path.join(OUT, 'geoman/leaflet-geoman.min.js'));
n += copy(need(path.join(NM, '@turf/turf/turf.min.js')), path.join(OUT, 'turf/turf.min.js'));

/* Firebase's compat builds, which are the ones that work without a bundler:
   they are UMD, so the bare require() inside only runs in the Node branch that
   a browser never takes, and they set the `firebase` global the app reads.
   firestore-compat is 547 KB, far the largest thing in vendor/, and it is
   here because the records now live in the database. The service worker
   precaches it, so it is downloaded once per device rather than per visit —
   and it has to be local anyway, since a farm with no signal cannot fetch a
   library before it can read its own task list. */
n += copy(need(path.join(NM, 'firebase/firebase-app-compat.js')), path.join(OUT, 'firebase/firebase-app-compat.js'));
n += copy(need(path.join(NM, 'firebase/firebase-auth-compat.js')), path.join(OUT, 'firebase/firebase-auth-compat.js'));
n += copy(need(path.join(NM, 'firebase/firebase-firestore-compat.js')), path.join(OUT, 'firebase/firebase-firestore-compat.js'));

/* One stylesheet out of the per-weight ones @fontsource ships: .woff dropped,
   ./files/x flattened to ./x so the whole family sits in one folder. */
const css = ['/* UT Turf Farm — fonts served from this folder, not from Google.',
             '   Generated by tools/build-vendor.js. Do not edit by hand. */', ''];
FONTS.forEach(f => {
  const base = need(path.join(NM, '@fontsource', f.pkg));
  f.weights.forEach(w => {
    let src = fs.readFileSync(need(path.join(base, w + '.css')), 'utf8');
    src = src.replace(/,\s*url\(\.\/files\/[^)]*\.woff\)\s*format\('woff'\)/g, '');
    src = src.split('./files/').join('./');
    css.push(src.trim(), '');
    const seen = {};
    src.replace(/url\(\.\/([^)]*\.woff2)\)/g, (_, file) => {
      if (seen[file]) return '';
      seen[file] = 1;
      n += copy(path.join(base, 'files', file), path.join(OUT, 'fonts', file));
      return '';
    });
  });
});
mkdir(path.join(OUT, 'fonts'));
fs.writeFileSync(path.join(OUT, 'fonts/fonts.css'), css.join('\n'));
n++;

console.log('vendor/ rebuilt — ' + n + ' files');
