/*
 * Writes sw.js — the service worker's precache list and its version.
 *
 * The version is a hash of the files themselves, not a number somebody has to
 * remember to bump. That matters more than it sounds: the classic way a PWA
 * fails is that a change ships, the cache name did not change, and every
 * installed device serves the old copy forever with no symptom except "it
 * didn't update" — which nobody can diagnose and nobody can fix from a phone.
 *
 * Because the version is derived, `npm run sw` after any change produces a new
 * one automatically, and tools/test-pwa.js fails if sw.js is stale — so the
 * mistake is caught at test time rather than in the field.
 *
 *   node tools/build-sw.js
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');

/* Everything the app needs to open with no network. Tiles and radar are not
   here on purpose — they are fetched live and handled at runtime below. */
const SHELL = ['UT-TurfFarm-App.html', 'farm-geo.js', 'manifest.webmanifest'];
const DIRS = ['vendor', 'icons'];

/* The app's own code — app-01-shell.js and the rest. FOUND, NOT LISTED, and
   that is the whole point: if somebody splits out a sixth file in 2030 and
   this were a hand-kept list, they would have to know to come and add it here.
   They would not know. The app would then work perfectly on their machine and
   fail to open on a phone with no signal, which is the hardest kind of bug to
   be told about from a field. */
function appFiles() {
  return fs.readdirSync(ROOT)
    .filter(f => /^app-\d\d-[a-z0-9-]+\.js$/.test(f))
    .sort();
}

function walk(dir, out) {
  fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true }).forEach(e => {
    const rel = dir + '/' + e.name;
    if (e.isDirectory()) walk(rel, out);
    else if (!/^\./.test(e.name) && !/\.md$/i.test(e.name)) out.push(rel);
  });
  return out;
}

/* Exported so tools/test-pwa.js computes the version exactly the same way this
   does, rather than keeping a second copy of the rule that could drift. */
function shellFiles() {
  const files = SHELL.concat(appFiles());
  DIRS.forEach(d => walk(d, files));
  return files.sort();
}
function shellVersion(files) {
  const h = crypto.createHash('sha256');
  /* THIS FILE COUNTS TOO — added 2026-08-27.
     The version used to be a hash of the precached files alone, so a change to
     the WORKER'S OWN behaviour (the fetch handler, what it leaves alone)
     shipped under the old version number. The new worker still installs, but
     nobody could look at a phone and tell which one it was running — which is
     exactly the question that mattered the day the shared database would not
     connect. The worker is generated from this file, so hashing this file
     covers it. test-pwa.js calls this same function, so the two cannot drift. */
  h.update(fs.readFileSync(__filename));
  (files || shellFiles()).forEach(f => {
    h.update(f);
    h.update(fs.readFileSync(path.join(ROOT, f)));
  });
  return h.digest('hex').slice(0, 12);
}
module.exports = { shellFiles, shellVersion };

if (require.main !== module) return;

const files = shellFiles();

const missing = files.filter(f => !fs.existsSync(path.join(ROOT, f)));
if (missing.length) { console.error('missing:\n  ' + missing.join('\n  ')); process.exit(1); }

const VERSION = shellVersion(files);

const sw = `/* GENERATED by tools/build-sw.js — do not edit by hand.
   Re-run \`npm run sw\` after changing the app, farm-geo.js, vendor/ or icons/.
   VERSION is a hash of those files, so it changes when they do. */
const VERSION = '${VERSION}';
const CACHE = 'ut-turf-farm-' + VERSION;
/* v2 on 2026-09-16: v1 stored every photo sealed (see tileFetch below) and a
   phone that ran out of room showed green squares. Renaming it is what makes
   activate() below throw the bloated v1 away. */
const TILES = 'ut-turf-tiles-v2';
const TILE_MAX = 400;          /* roughly a few sessions of panning */

const SHELL = ${JSON.stringify(files, null, 2).split('\n').join('\n')};

/* Install: fetch the whole shell before this worker is allowed to take over.
   No skipWaiting here — the page asks the user first, so a crew member is not
   reloaded out from under a half-filled form. */
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)));
});

/* Activate: drop every older version of the shell. The tile cache is keyed
   separately and deliberately survives — re-downloading imagery costs the farm
   data for no benefit. */
self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE && k !== TILES).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', e => {
  if (e.data === 'SKIP_WAITING') self.skipWaiting();
  if (e.data === 'VERSION') e.source && e.source.postMessage({ version: VERSION });
});

const isTile = u => /server\\.arcgisonline\\.com/.test(u);
/* The radar loop is a live picture; a cached one is a lie about the weather. */
const isLive = u => /radar\\.weather\\.gov/.test(u);

/* Is this a request for one of OUR OWN files? Anything else belongs to another
   website and this worker must not stand in front of it -- see the fetch
   handler below. A URL we cannot even parse is treated as ours, because that
   keeps the old behaviour for anything we might have precached. */
const isOurs = u => {
  try { return new URL(u, self.location.href).origin === self.location.origin; }
  catch (err) { return true; }
};

/* Ask the imagery server for the photo OPENLY (cors), not the way the map
   itself asks for it.

   The map's plain <img> request gets back a sealed ("opaque") reply: the
   picture works, but the phone is not allowed to know how big it is, so it
   books every one against the app's storage as several megabytes to be safe.
   Measured on 2026-09-16: 30 photos of about 10 KB each booked 225 MB. With
   up to 400 kept, a phone ran out of room within a few screens of panning --
   and from then on every photo arrived and was then thrown away, which is the
   green squares on the map. The Esri server allows open requests, so asking
   that way stores the real 10 KB. If an open request is ever refused, fall
   back to the sealed one: a photo on screen matters more than a saved one. */
async function tileFetch(req) {
  try { return await fetch(req.url, { mode: 'cors', credentials: 'omit' }); }
  catch (err) { return fetch(req); }
}

/* Saving a photo is a nice-to-have. It must never be able to cost the photo
   itself, so every failure in here is swallowed -- the caller has already
   handed the picture to the map. */
async function tileKeep(url, res) {
  try {
    const c = await caches.open(TILES);
    await c.put(url, res);
    const keys = await c.keys();
    if (keys.length > TILE_MAX) await Promise.all(keys.slice(0, keys.length - TILE_MAX).map(k => c.delete(k)));
  } catch (err) {}
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = req.url;

  if (isLive(url)) return;                       /* straight to the network */

  if (isTile(url)) {
    /* Imagery already seen keeps working in a dead spot. */
    e.respondWith((async () => {
      const hit = await caches.match(url);
      if (hit) return hit;
      let res;
      try { res = await tileFetch(req); }
      catch (err) { return new Response('', { status: 504 }); }
      /* Only a real, readable photo is worth keeping; a sealed fallback would
         bring the storage problem straight back. */
      if (res.ok && res.type !== 'opaque') e.waitUntil(tileKeep(url, res.clone()));
      return res;
    })());
    return;
  }

  /* SOMEBODY ELSE'S WEBSITE: hands off, straight to the network.
     -------------------------------------------------------------------
     This line is load-bearing and it was missing until 2026-08-27.

     The shared database does not fetch a page and finish. It holds ONE
     long request open to Google and Google pushes changes down it as they
     happen. Answering that request through e.respondWith() below breaks
     it: the reply is collected here and handed over in one piece at the
     end, and there is no end, so the app waits forever. It never errors --
     it just never hears back.

     The symptom, and it cost a day: every drawer stuck on "Connected --
     waiting for the shared copy", nothing red, and nothing ever uploaded,
     because a phone deliberately sends nothing up until it has heard from
     the shared copy once. Signing in still worked, which made the
     connection look fine -- sign-in is a POST, and POSTs never reach this
     handler at all (see the first line above).

     Map imagery is the one deliberate exception and it is handled above,
     before this line. Everything else off this site -- Google, the
     weather -- goes straight out. */
  if (!isOurs(url)) return;

  /* A navigation always lands on the app, even offline. */
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try { return await fetch(req); }
      catch (err) { return (await caches.match('UT-TurfFarm-App.html')) || Response.error(); }
    })());
    return;
  }

  /* Everything else on this site: the cache is the source of truth for this
     version, since the shell is versioned as a set and cannot be half-old. */
  e.respondWith((async () => {
    const hit = await caches.match(req, { ignoreSearch: false });
    if (hit) return hit;
    try { return await fetch(req); }
    catch (err) { return new Response('', { status: 504 }); }
  })());
});
`;

fs.writeFileSync(path.join(ROOT, 'sw.js'), sw);
console.log('sw.js written — version ' + VERSION + ', ' + files.length + ' files precached');
