/*
 * Writes sw.js — the service worker's precache list and its version.
 *
 * The version is a hash of the files themselves, not a number somebody has to
 * remember to bump. That matters more than it sounds: the classic way a PWA
 * fails is that a change ships, the cache name did not change, and every
 * installed device serves the old copy forever with no symptom except "it
 * didn't update" — which nobody can diagnose and nobody can fix from a phone.
 *
 * Because the version is derived, `npm run sw` after any change produces a new
 * one automatically, and tools/test-pwa.js fails if sw.js is stale — so the
 * mistake is caught at test time rather than in the field.
 *
 *   node tools/build-sw.js
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');

/* Everything the app needs to open with no network. Tiles and radar are not
   here on purpose — they are fetched live and handled at runtime below. */
const SHELL = ['UT-TurfFarm-App.html', 'farm-geo.js', 'manifest.webmanifest'];
const DIRS = ['vendor', 'icons'];

function walk(dir, out) {
  fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true }).forEach(e => {
    const rel = dir + '/' + e.name;
    if (e.isDirectory()) walk(rel, out);
    else if (!/^\./.test(e.name) && !/\.md$/i.test(e.name)) out.push(rel);
  });
  return out;
}

/* Exported so tools/test-pwa.js computes the version exactly the same way this
   does, rather than keeping a second copy of the rule that could drift. */
function shellFiles() {
  const files = SHELL.slice();
  DIRS.forEach(d => walk(d, files));
  return files.sort();
}
function shellVersion(files) {
  const h = crypto.createHash('sha256');
  (files || shellFiles()).forEach(f => {
    h.update(f);
    h.update(fs.readFileSync(path.join(ROOT, f)));
  });
  return h.digest('hex').slice(0, 12);
}
module.exports = { shellFiles, shellVersion };

if (require.main !== module) return;

const files = shellFiles();

const missing = files.filter(f => !fs.existsSync(path.join(ROOT, f)));
if (missing.length) { console.error('missing:\n  ' + missing.join('\n  ')); process.exit(1); }

const VERSION = shellVersion(files);

const sw = `/* GENERATED by tools/build-sw.js — do not edit by hand.
   Re-run \`npm run sw\` after changing the app, farm-geo.js, vendor/ or icons/.
   VERSION is a hash of those files, so it changes when they do. */
const VERSION = '${VERSION}';
const CACHE = 'ut-turf-farm-' + VERSION;
const TILES = 'ut-turf-tiles-v1';
const TILE_MAX = 400;          /* roughly a few sessions of panning */

const SHELL = ${JSON.stringify(files, null, 2).split('\n').join('\n')};

/* Install: fetch the whole shell before this worker is allowed to take over.
   No skipWaiting here — the page asks the user first, so a crew member is not
   reloaded out from under a half-filled form. */
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)));
});

/* Activate: drop every older version of the shell. The tile cache is keyed
   separately and deliberately survives — re-downloading imagery costs the farm
   data for no benefit. */
self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE && k !== TILES).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', e => {
  if (e.data === 'SKIP_WAITING') self.skipWaiting();
  if (e.data === 'VERSION') e.source && e.source.postMessage({ version: VERSION });
});

const isTile = u => /server\\.arcgisonline\\.com/.test(u);
/* The radar loop is a live picture; a cached one is a lie about the weather. */
const isLive = u => /radar\\.weather\\.gov/.test(u);

async function tilePut(req, res) {
  const c = await caches.open(TILES);
  await c.put(req, res.clone());
  const keys = await c.keys();
  if (keys.length > TILE_MAX) await Promise.all(keys.slice(0, keys.length - TILE_MAX).map(k => c.delete(k)));
  return res;
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = req.url;

  if (isLive(url)) return;                       /* straight to the network */

  if (isTile(url)) {
    /* Imagery already seen keeps working in a dead spot. */
    e.respondWith((async () => {
      const hit = await caches.match(req);
      if (hit) return hit;
      try { return await tilePut(req, await fetch(req)); }
      catch (err) { return new Response('', { status: 504 }); }
    })());
    return;
  }

  /* A navigation always lands on the app, even offline. */
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try { return await fetch(req); }
      catch (err) { return (await caches.match('UT-TurfFarm-App.html')) || Response.error(); }
    })());
    return;
  }

  /* Everything else: the cache is the source of truth for this version, since
     the shell is versioned as a set and cannot be half-old. */
  e.respondWith((async () => {
    const hit = await caches.match(req, { ignoreSearch: false });
    if (hit) return hit;
    try { return await fetch(req); }
    catch (err) { return new Response('', { status: 504 }); }
  })());
});
`;

fs.writeFileSync(path.join(ROOT, 'sw.js'), sw);
console.log('sw.js written — version ' + VERSION + ', ' + files.length + ' files precached');
